root = "."
testdata_dir = "testdata"
tmp_dir = "/tmp/air-nexus"

[build]
  bin = "/tmp/air-nexus/server"
  cmd = "go build -o /tmp/air-nexus/server ./cmd/nexus"
  delay = 500
  exclude_dir = ["node_modules", "cmd/gallery", "cmd/install", "cmd/boundarytoken", "cmd/nexus/visual-tests", "cmd/nexus-compare", "staticfs", "galleryruntime"]
  exclude_regex = ["_test.go", "_templ.go"]
  include_ext = ["go", "templ", "css"]
  kill_delay = "2s"
  include_dir = ["cmd/nexus", "components", "assets"]
  stop_on_error = false

[log]
  time = true

[misc]
  clean_on_exit = false
