// Code generated by boundarytoken. DO NOT EDIT.
// Source: github.com/emergent-company/go-daisy/components/layout

package gallery

import "github.com/emergent-company/go-daisy/galleryruntime"

// NavbarTokens returns the DesignToken slice for NavbarWithBoundary.
func NavbarTokens() []galleryruntime.DesignToken {
	return []galleryruntime.DesignToken{
		{
			Label:      "App Name",
			Group:      "Component",
			Type:       galleryruntime.TokenTypeText,
			Default:    "MyApp",
			QueryParam: "appName",
		},
	}
}
